changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚀 Features"
      labels:
        - feature
        - enhancement
    - title: "🐛 Fixes"
      labels:
        - fix
        - bug
    - title: "🎨 UI / UX"
      labels:
        - ui
        - ux
        - design
    - title: "🧱 Refactor"
      labels:
        - refactor
    - title: "📚 Documentation"
      labels:
        - docs
        - documentation
    - title: "⚙️ CI / Tooling"
      labels:
        - ci
        - tooling
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"